POST {{host}}/{{application_folder}}/index.{{file_extension}}
Content-Type: application/x-www-form-urlencoded

id=99&content=new-element

###
POST {{host}}/{{application_folder}}/index.{{file_extension}}
Content-Type: application/json

{
  "id": 999,
  "value": "content"
}

###
